version: '2'

volumes:
  database:
  static_files:
  media_files:

services:
  web:
    build: web/
    restart: always
    depends_on:
      - database
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=0 # log into console
      - DEBUG=True
      - DATABASE_NAME=openeats
      - DATABASE_USER=openeats
      - DATABASE_PASSWORD=admin
      - TIME_ZONE=Europe/Madrid
      - ALLOWED_HOST=127.0.0.1
      - SECRET_KEY=tk1igapawp92muz4vw4g5q20nosgce11bw2s343jouyq9ljgk33jh
      - OETITLE=OpenEats2 Dev
    volumes:
      - ./web:/usr/src/app/

  database:
    image: postgres:9.6
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql
    environment:
      - POSTGRES_DB=openeats
      - POSTGRES_USER=openeats
      - POSTGRES_PASSWORD=admin
    expose:
      - "5432"
