version: '2'

volumes:
  database:
  node_modules:
  static-files:
  site-media:

services:
  db:
    image: mariadb
    restart: unless-stopped
    network_mode: bridge
    environment:
      - MYSQL_ROOT_PASSWORD=Onz4sD3Ch0colat3
      - MYSQL_DATABASE=openeats
    volumes:
      - database:/var/lib/mysql
    expose:
      - "3306"

  api:
    image: openeats/api
    restart: always
    network_mode: bridge
    environment:
      - NODE_URL=node:8080
      - DJANGO_TIME_ZONE=Europe/Madrid
      - DJANGO_SECRET_KEY=7-z^#7xy_x!8t3^w#@w=)k)a^^b_k*m7-8y!)sm#4u5
      - DJANGO_SETTINGS_MODULE=base.settings
      - DJANGO_DEBUG=
      - API_URL=localhost:8000
      - MYSQL_DATABASE=openeats
      - MYSQL_ROOT_PASSWORD=Onz4sD3Ch0colat3
    volumes:
      - static-files:/code/static-files
      - site-media:/code/site-media
    expose:
      - "8000"
    depends_on:
      - db
    command: ./base/gunicorn_start.sh

  node:
    image: openeats/node
    restart: unless-stopped
    network_mode: bridge
    environment:
      - API_URL=localhost:8000
      - NODE_ENV=production
      - NODE_API_URL=http://localhost:8080
      #- NODE_PORT=8080
      - NODE_LOCALE=es
    volumes:
      - node_modules:/code/node_modules
    expose:
      - "8080"
    depends_on:
      - api
    command: npm start

  nginx:
    image: openeats/nginx
    restart: unless-stopped
    network_mode: bridge
    environment:
      - VIRTUAL_HOST=recetas.grigri.cloud
      - LETSENCRYPT_HOST=recetas.grigri.cloud
      - LETSENCRYPT_EMAIL=pando855@gmail.com
    volumes:
      - static-files:/var/www/html/openeats-static/static-files
      - site-media:/var/www/html/openeats-static/site-media
    ports:
      - "80:80"
    depends_on:
      - api
      - node
    #TODO: For whatever reason the env vars are not being read correctly. They need to be manually replaace below.
    # Sed replace the API_PORT and NODE_PORT vars so nginx can serve them.
    command: /bin/bash -c "sed -i 's/API_PORT/8000/g' /etc/nginx/conf.d/default.conf && sed -i 's/NODE_PORT/8080/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
